---
name: Upload To Azure Blob Storage
on: pull_request
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: echo "hello" > world.txt
      - name: Upload all PNGs to Azure Blob Storage
        id: upload
        uses: github-developer/upload-azure-blob@v1
        with:
          account: octodex
          destination: octocats
          source: 'world.txt'
